
DEFINE input:inference "ont.cpi"

PREFIX ent:  <http://codinuum.com/fact/entity/>
PREFIX rel:  <http://codinuum.com/fact/version/release/>
PREFIX ext:  <http://codinuum.com/fact/external/>
PREFIX src:  <http://codinuum.com/ontologies/2012/10/source-code-entity#>
PREFIX ver:  <http://codinuum.com/ontologies/2012/10/versioning#>
PREFIX chg:  <http://codinuum.com/ontologies/2012/10/primitive-change#>
PREFIX java: <http://codinuum.com/ontologies/2012/10/java-entity#>
PREFIX c:    <http://codinuum.com/ontologies/2012/10/c-entity#>


INSERT {
  ?x java:declaredBy ?fh .
}
WHERE {

  FILTER NOT EXISTS {
    ?x java:declaredBy [] .
  }

  ?for a java:EnhancedForStatement ;
       src:child2 ?body ;
       src:child0 ?fh .

  ?fh a java:ForHeader ;
      java:name ?vname .

  ?x a java:Name ;
     java:name ?vname ;
     src:parent+ ?body .

}
